#!/usr/bin/env bash

set -e

PROGRAMS=(bash fonts i3 mpdnotify oh-my-zsh synaptic xresources cava gtk-2.0 gtk-3.0 livestreamer 
mps-youtube ncmpcpp ranger tmux zsh compton nano mpd mpv neofetch sublime3 xfce4)
HOME='/home/rook'

for program in ${PROGRAMS[@]}; do
  stow --target=/home/rook $program
  echo "Configuring $program"
done

echo "Done!"
